services:
  n8n:
    image: 'build'
    environment:
      N8N_EDITOR_BASE_URL: '${SERVICE_FQDN_N8N}'
      WEBHOOK_URL: '${SERVICE_FQDN_N8N}'
      N8N_HOST: '${SERVICE_URL_N8N}'
      GENERIC_TIMEZONE: '${GENERIC_TIMEZONE:-Europe/Madrid}'
      TZ: '${TZ:-Europe/Madrid}'
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: '${POSTGRES_DB:-n8n}'
      DB_POSTGRESDB_HOST: postgresql
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_USER: $SERVICE_USER_POSTGRES
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: 'true'
      SERVICE_URL_N8N: '${SERVICE_URL_N8N}'
      COOLIFY_RESOURCE_UUID: esoc0o00ww48kwcgokkggcss
      COOLIFY_CONTAINER_NAME: n8n-esoc0o00ww48kwcgokkggcss
      COOLIFY_URL: 'https://n8n.mrodas.es'
      COOLIFY_FQDN: n8n.mrodas.es
    volumes:
      - 'esoc0o00ww48kwcgokkggcss_n8n-data:/home/node/.n8n'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
    container_name: n8n-esoc0o00ww48kwcgokkggcss
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.serviceId=1
      - coolify.type=service
      - coolify.name=n8n-esoc0o00ww48kwcgokkggcss
      - coolify.resourceName=n8n
      - coolify.projectName=automatizaciones
      - coolify.serviceName=n8n
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=1
      - coolify.service.subType=application
      - coolify.service.subName=n8n
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-esoc0o00ww48kwcgokkggcss-n8n.entryPoints=http
      - traefik.http.routers.http-0-esoc0o00ww48kwcgokkggcss-n8n.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-esoc0o00ww48kwcgokkggcss-n8n.rule=Host(`n8n.mrodas.es`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-esoc0o00ww48kwcgokkggcss-n8n.service=http-0-esoc0o00ww48kwcgokkggcss-n8n
      - traefik.http.routers.https-0-esoc0o00ww48kwcgokkggcss-n8n.entryPoints=https
      - 'traefik.http.routers.https-0-esoc0o00ww48kwcgokkggcss-n8n.rule=Host(`n8n.mrodas.es`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-esoc0o00ww48kwcgokkggcss-n8n.service=https-0-esoc0o00ww48kwcgokkggcss-n8n
      - traefik.http.routers.https-0-esoc0o00ww48kwcgokkggcss-n8n.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-esoc0o00ww48kwcgokkggcss-n8n.tls=true
      - traefik.http.services.http-0-esoc0o00ww48kwcgokkggcss-n8n.loadbalancer.server.port=5678
      - traefik.http.services.https-0-esoc0o00ww48kwcgokkggcss-n8n.loadbalancer.server.port=5678
      - 'caddy_0.handle.0_reverse_proxy={{upstreams 5678}}'
      - 'caddy_0.handle=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://n8n.mrodas.es'
      - caddy_ingress_network=esoc0o00ww48kwcgokkggcss
    networks:
      esoc0o00ww48kwcgokkggcss: null
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'esoc0o00ww48kwcgokkggcss_postgresql-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: $SERVICE_USER_POSTGRES
      POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      POSTGRES_DB: '${POSTGRES_DB:-n8n}'
      COOLIFY_RESOURCE_UUID: esoc0o00ww48kwcgokkggcss
      COOLIFY_CONTAINER_NAME: postgresql-esoc0o00ww48kwcgokkggcss
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
    container_name: postgresql-esoc0o00ww48kwcgokkggcss
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.serviceId=1
      - coolify.type=service
      - coolify.name=postgresql-esoc0o00ww48kwcgokkggcss
      - coolify.resourceName=n8n
      - coolify.projectName=automatizaciones
      - coolify.serviceName=postgresql
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=1
      - coolify.service.subType=database
      - coolify.service.subName=postgresql
    networks:
      esoc0o00ww48kwcgokkggcss: null
volumes:
  esoc0o00ww48kwcgokkggcss_n8n-data:
    name: esoc0o00ww48kwcgokkggcss_n8n-data
  esoc0o00ww48kwcgokkggcss_postgresql-data:
    name: esoc0o00ww48kwcgokkggcss_postgresql-data
networks:
  esoc0o00ww48kwcgokkggcss:
    name: esoc0o00ww48kwcgokkggcss
    external: true
configs: {  }
secrets: {  }